### PR TITLE
Awesome typescript was complaining that backend is an unused property.

### PR DESCRIPTION
**Pull request by SebastianStehle**

### CODE REVIEW

**Comment by DarkXaHTeP** [comment]
@SebastianStehle could you please tell about the reasons for this change? It doesn't make any sense to me at the moment and breaks the build due to changes in dependencies order (you need to update factory inside progress-http.module as well). Thanks!

**Comment by SebastianStehle** [comment]
Sorry, changing the order was stupid. The reason for the change is that the typescript compiler is complaining about an unused property "backend".

**Comment by DarkXaHTeP** [comment]
@SebastianStehle Thanks for the explanation. Just update the order in [module declaration](https://github.com/DarkXaHTeP/angular-progress-http/blob/master/src/lib/progress-http.module.ts) as well and it should work

**Comment by DarkXaHTeP** [comment]
@SebastianStehle thanks for the fixes! I'll double check that everything is fine later today and let you know

**Comment by DarkXaHTeP** [comment]
@SebastianStehle published your changes to npm as 0.4.1

**Comment by SebastianStehle** [comment]
Awesome, thanks.

**Pull request merged**
